### PR TITLE
Refactor allocated project to directly incurred

### LINKED ISSUE #202: Project type should be called 'Directly Incurred'
Allocated is generally an academic member of staff.

- [x] Backup database
- [x] Rename the AllocatedProject model and other parts of the application, e.g. Form
- [x] Apply migrations
- [x] Verify data

### PR DESCRIPTION
**Pull request by yld-weng**
Django have cleverly asked whether I have renamed the model. All data are preserved. No errors arise during the process.

Close #202.

### CODE REVIEW

**Comment by davidwilby** [comment]
Looks straightforward enough!

Is the term 'Directly Incurred' intelligible to anyone who doesn't work in university finance? Presumably the word 'allocated' was chosen originally since it means that someone is allocated to the project? But has an unfortunate clash with how the term is used in finance according to #202, is that right?

Should we add some short explanation somewhere if required?

I just want to try to avoid RSE admin falling into the trap of so many university finance tools that are completely unintelligible to anyone outside of uni finance, if at all possible.

**Comment by yld-weng** [comment]
> Looks straightforward enough!
> 
> Is the term 'Directly Incurred' intelligible to anyone who doesn't work in university finance? Presumably the word 'allocated' was chosen originally since it means that someone is allocated to the project? But has an unfortunate clash with how the term is used in finance according to #202, is that right?

Yes, to quote the exact requirement:

> Project types don't fit with terminology used at UoS, Allocated is generally an academic member of staff rather than charged to the grant. Change project types to be called 'service' and Directly Incurred (rather than calling it allocated).

> Should we add some short explanation somewhere if required?
> 
> I just want to try to avoid RSE admin falling into the trap of so many university finance tools that are completely unintelligible to anyone outside of uni finance, if at all possible.

This is a good idea, I'll add this along with some other changes in the doc.

**Comment by davidwilby** [comment]
Awesome, thanks @yld-weng!

**Comment by yld-weng** [comment]
Also added a message to notify the new change

image

**Comment by davidwilby** [comment]
Neat, didn't know you could do this. I should do this more often.

**Comment by twinkarma** [comment]
Agree with @davidwilby. Since there's only 2 options it should be ok to just put the description in small grey text directly above or below the selector box, we can also use a tooltip/popover if we want to hide it and make it neater.

**Comment by yld-weng** [comment]
image

Updated with description

**Comment by yld-weng** [comment]
@davidwilby  @twinkarma I will merge this PR soon if there are no other suggestions

**Pull request merged**
